version: '2'
services:
  mapas:
    build:
      context: ../
      dockerfile: dev/Dockerfile

    env_file:
      - ../.env

    command: /var/www/dev/start.sh

    ports:
      - "80:80"

    volumes:
      - ../docker-data/assets:/var/www/html/assets
      - ../docker-data/public-files:/var/www/html/files
      - ../docker-data/private-files:/var/www/var/private-files
      - ../docker-data/logs:/var/www/var/logs

      - ../docker/config/authentication.php:/var/www/config/authentication.php
      - ../docker/config/common.d/plugins.php:/var/www/config/common.d/plugins.php

      - ../app-backups:/app-backups

      # themes and plugins
      - ../plugins/MultipleLocalAuth:/var/www/src/plugins/MultipleLocalAuth
      - ../plugins/AdminLoginAsUser:/var/www/src/plugins/AdminLoginAsUser
      - ../plugins/RecreatePCacheOnLogin:/var/www/src/plugins/RecreatePCacheOnLogin
      - ../plugins/SpamDetector:/var/www/src/plugins/SpamDetector
      - ../plugins/Accessibility:/var/www/src/plugins/Accessibility
      - ../themes/MapasMT:/var/www/src/themes/MapasMT

    depends_on:
      - db
      - redis
      - mailhog

    stdin_open: true
    tty: true


  redis:
    image: redis:6
    command: --maxmemory 256Mb --maxmemory-policy allkeys-lru

  db:
    image: postgis/postgis:14-master
    environment:
      - POSTGRES_PASSWORD=mapas
      - POSTGRES_USER=mapas
      - POSTGRES_DB=mapas
    ports:
      - "5432:5432"
    volumes:
      - ../docker/db:/docker-entrypoint-initdb.d
      - ../docker-data/db-data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
